# yamllint disable rule:line-length
# yamllint disable rule:indentation
# yamllint disable rule:comments-indentation
# too many spelling things, spell-checker: disable
---
- module-name: "app"
  data-files:
    - dirs:
        - "../themes"
        - "../locales"
    - patterns:
        - "../update.sh"
        - "../update.bat"
        - "../setup_web_channel_script.js"

  dlls:
    - from_filenames:
        relative_path: "../todds"
        prefixes:
          - "todds"
        executable: "yes"
      dest_path: "todds"
    - from_filenames:
        relative_path: "../libs"
        prefixes:
          - "steam*"
          - "Steam*"
          - "rimsort_steam*"
        suffixes:
          - "dll"
      dest_path: "."
      when: "win32"
    - from_filenames:
        relative_path: "../libs"
        prefixes:
          - "libsteam*"
          - "Steam*"
          - "rimsort_steam*"
        suffixes:
          - "so"
      dest_path: "."
      when: "linux"
    - from_filenames:
        relative_path: "../libs"
        prefixes:
          - "rimsort_steam*"
        suffixes:
          - "dylib"
      dest_path: "."
      when: "macos"
    - from_filenames:
        relative_path: "../libs"
        prefixes:
          - "libsteam*"
        suffixes:
          - "dylib"
      dest_path: "."
      when: "macos"

  options:
    checks:
      - description: "Mac Specific Build Options"
        macos_bundle: "yes"
        macos_bundle_as_onefile: "no"
        when: "macos"
