name: Bug Report
description: Create a bug report to help us improve
labels: ["bugs 🪲"]
body:
  - type: markdown
    attributes:
      value: |
        Create a bug report to help us improve
  - type: dropdown
    id: release_type
    attributes:
      label: Release Type
      description: What release type(s) are you using?
      multiple: true
      options:
        - Compiled (Windows x86-64)
        - Compiled (Darwin x86-64)
        - Compiled (Darwin ARM64)
        - Compiled (Ubuntu 22.04)
        - Compiled (Ubuntu 24.04)
        - Self-Compiled
        - Python Interpreter
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using? Please include the commit hash if you're not using a pre-compiled release.
      placeholder: Version number/Commit hash (e.g., v1.0.9, b010fe5)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What Operating System are you using? Please include your CPU architecture if on MacOS and desktop environment if on Linux.
      placeholder: Windows 11, macOS (ARM64), Arch (KDE), etc.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Relevant logs
      description: Please provide a RimSort.log file. There may be circumstances where a log file is not generated but without logs, it is difficult to diagnose the issue.
      placeholder: Link to RimSort.log file

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: Please clearly and concisely describe the bug you encountered. Also, provide steps to reproduce the bug.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: extra_info
    attributes:
      label: Additional context
      description: Add additional context about the problem here.
      placeholder: Additional context about the problem.

  - type: dropdown
    id: coc_terms
    attributes:
      multiple: true
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/RimSort/RimSort/blob/main/CODE_OF_CONDUCT.md).
      options:
        - I agree to follow this project's Code of Conduct
    validations:
      required: true

  - type: dropdown
    id: dup_terms
    attributes:
      multiple: true
      label: Duplicate Issue Check
      description: By submitting this issue, you attest that you've searched for similar [issues on GitHub](https://github.com/RimSort/RimSort/issues) and didn't find any.
      options:
        - I've checked for similar issues and didn't find anything
    validations:
      required: true

  - type: dropdown
    id: wiki_terms
    attributes:
      multiple: true
      label: Wiki/FAQ Check
      description: By submitting this issue, you attest that you've checked [the Wiki](https://github.com/RimSort/RimSort/wiki) for potential solutions and didn't find any.
      options:
        - I've checked the Wiki for a solution and didn't find a solution
    validations:
      required: true
