blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://rimsort.github.io/RimSort/
    about: Please check the Wiki for usage/contribution instructions, as well as solutions to common issues.
  - name: Discord
    url: https://discord.gg/ErTaTRwrTm
    about: Visit our Discord server for discussions, extra support, and community interaction.
