# Auto build on push to main and PR.
# Not recommended to release these builds due to versioning.

name: Auto Build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - master
    paths:
      - "app/**"
      - "distribute.py"
      - "requirements*.txt"

permissions: {}

jobs:
  pre-test:
    permissions: 
      contents: read
    uses: ./.github/workflows/pytest.yml

  pre-build:
    uses: ./.github/workflows/get_version_info.yml
    with:
      format_only: true

  cleanup:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enhanced Cleanup
        shell: bash
        run: |
          TARGET_DIR="build/__main__.app/Contents/Resources/qtwebengine_locales"
          if [ -d "$TARGET_DIR" ]; then
            echo "Attempting to remove directory..."
            # Check for open files and terminate processes if needed
            lsof +D "$TARGET_DIR" || echo "No processes using the directory."
            lsof +D "$TARGET_DIR" | awk '{print $2}' | xargs -r kill -9 || echo "Failed to terminate some processes."
            
            # Set write permissions and attempt deletion
            chmod -R u+w "$TARGET_DIR" || echo "Failed to set write permissions."
            rm -rf "$TARGET_DIR" || echo "Failed to delete directory."

            # Retry mechanism
            for i in {1..3}; do
              if [ -d "$TARGET_DIR" ]; then
                echo "Retrying directory cleanup (Attempt $i)..."
                chmod -R u+w "$TARGET_DIR"
                rm -rf "$TARGET_DIR"
                sleep 5
              else
                break
              fi
            done

            # Final check
            if [ -d "$TARGET_DIR" ]; then
              echo "Directory cleanup failed after retries. Exiting."
              exit 1
            else
              echo "Directory successfully removed."
            fi
          else
            echo "Directory does not exist; no cleanup needed."
          fi

      - name: Debug Directory State
        shell: bash
        run: ls -la build/__main__.app/Contents/Resources/qtwebengine_locales || echo "Directory does not exist"

  attested-build:
    needs: [pre-build, cleanup]
    if: github.event_name != 'pull_request'
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      version_format: ${{ needs.pre-build.outputs.version_format }}
      attest: true

  non-attested-build:
    needs: [pre-build, cleanup]
    if: github.event_name == 'pull_request'
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      version_format: ${{ needs.pre-build.outputs.version_format }}
      attest: false
