name: Run Pytest
on:
  workflow_call: null
  workflow_dispatch: null
  merge_group:

permissions: {}

jobs:
  run-tests:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Dependencies
        shell: bash
        run: uv sync --locked --dev

      - name: Install special python dependencies
        shell: bash
        run: |
          set -e
          uv run --frozen python \
          ./distribute.py \
          --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install missing Linux libs for gui tests
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libegl-dev libgl1 libglx-mesa0 libglib2.0-0 xvfb libxcb-cursor-dev
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0
        shell: bash

      - name: Test with pytest
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            export QT_QPA_PLATFORM=offscreen
          fi
          uv run pytest --doctest-modules --junitxml=junit/test-results.xml --cov=app --cov-report=xml --cov-report=html -s --no-qt-log
        shell: bash
        env:
          QT_DEBUG_PLUGINS: "1"
          PYTHONIOENCODING: "utf-8"

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v7
        with:
          name: pytest-results-${{ matrix.os }}
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

  pytest:
    needs: [run-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "$RESULT" != "success" ]; then
            echo "Tests failed on one or more platforms"
            exit 1
          fi
        env:
          RESULT: ${{ needs.run-tests.result }}
